//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Price { get; set; }
        public string Descriptoin { get; set; }
        public string Image { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual TypeMenu TypeMenu { get; set; }
    }
}
